spring:
  application:
    name: gateway

server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
              
zuul:
  routes:
    service:
      path: /service/**
      serviceId: uservice
    uservice2:
      path: /service2/**
      service-id: uservice2